// ============================================================================
// SUMBER DATA UTAMA — Direktori Guru & Pegawai
// ----------------------------------------------------------------------------
// Data tenaga pendidik, tenaga kependidikan, dan staf pendukung dikelola di
// satu pintu ini. Identitas instansi mengikuti `namaSekolah` dari
// `dataSekolah.ts` agar selalu sinkron dengan sumber utama profil sekolah.
// Dipakai oleh: GuruPegawaiPage.tsx
// ============================================================================
import { namaSekolah } from './dataSekolah';

export interface GuruPegawaiItem {
  id: number;
  nama: string;
  nip: string;
  nuptk: string;
  statusKepegawaian: string;
  pendidikan: string;
  jabatan: string;
  status: 'Guru' | 'Pegawai' | 'Satpam';
  mataPelajaran?: string;
  jenisKelamin: 'Laki-laki' | 'Perempuan';
  agama: string;
  tempatTanggalLahir: string;
  alamat: string;
  kodepos: string;
  telepon: string;
  instansi: string;
  umur: string;
  keterangan: string;
  foto?: string;
  tingkatan: number;
  tingkatLabel: string;
}

const instansi = namaSekolah;

export const dataGuruPegawai: GuruPegawaiItem[] = [
  {
    id: 1,
    nama: 'Drs. H. Surya Darma, M.Pd.',
    nip: '196512121990031001',
    nuptk: '1234567890123456',
    statusKepegawaian: 'PNS / Pembina Utama Muda',
    pendidikan: 'S2 Magister Pendidikan',
    jabatan: 'Kepala Sekolah',
    status: 'Guru',
    mataPelajaran: 'Pendidikan Agama Islam',
    jenisKelamin: 'Laki-laki',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 12 Desember 1965',
    alamat: 'Jl. Utama No. 12, Sijunjung',
    kodepos: '27511',
    telepon: '08123456789',
    instansi,
    umur: '60 Tahun',
    keterangan: 'Aktif',
    foto: 'images/GuruPegawai/kepala-sekolah.jpg',
    tingkatan: 1,
    tingkatLabel: 'Pimpinan',
  },
  {
    id: 2,
    nama: 'Dra. Sri Hartati',
    nip: '197003151995022001',
    nuptk: '2345678901234567',
    statusKepegawaian: 'PNS',
    pendidikan: 'S1 Sastra Indonesia',
    jabatan: 'Wakil Kepala Sekolah Bidang Kurikulum',
    status: 'Guru',
    mataPelajaran: 'Bahasa Indonesia',
    foto: 'images/GuruPegawai/guru-1.jpg',
    jenisKelamin: 'Perempuan',
    agama: 'Islam',
    tempatTanggalLahir: 'Padang, 15 Maret 1970',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '56 Tahun',
    keterangan: '-',
    tingkatan: 2,
    tingkatLabel: 'Wakil Kepala Sekolah',
  },
  {
    id: 3,
    nama: 'Drs. Bambang Santoso',
    nip: '196808081992031002',
    nuptk: '3456789012345678',
    statusKepegawaian: 'PNS',
    pendidikan: 'S1 Pendidikan Jasmani',
    jabatan: 'Wakil Kepala Sekolah Bidang Kesiswaan',
    status: 'Guru',
    mataPelajaran: 'Pendidikan Jasmani',
    foto: 'images/GuruPegawai/guru-2.jpg',
    jenisKelamin: 'Laki-laki',
    agama: 'Islam',
    tempatTanggalLahir: 'Solok, 08 Agustus 1968',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '57 Tahun',
    keterangan: '-',
    tingkatan: 2,
    tingkatLabel: 'Wakil Kepala Sekolah',
  },
  {
    id: 4,
    nama: 'Siti Aminah, S.Pd.',
    nip: '198505052010012005',
    nuptk: '-',
    statusKepegawaian: 'PNS',
    pendidikan: 'S1 Pendidikan Matematika',
    jabatan: 'Guru Matematika',
    status: 'Guru',
    mataPelajaran: 'Matematika',
    foto: 'images/GuruPegawai/guru-3.jpg',
    jenisKelamin: 'Perempuan',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 05 Mei 1985',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '41 Tahun',
    keterangan: '-',
    tingkatan: 4,
    tingkatLabel: 'Guru',
  },
  {
    id: 5,
    nama: 'Ahmad Fauzi, S.Pd.',
    nip: '198712122011011003',
    nuptk: '-',
    statusKepegawaian: 'PNS',
    pendidikan: 'S1 Pendidikan Fisika',
    jabatan: 'Guru IPA',
    status: 'Guru',
    mataPelajaran: 'Ilmu Pengetahuan Alam',
    foto: 'images/GuruPegawai/guru-4.jpg',
    jenisKelamin: 'Laki-laki',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 12 Desember 1987',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '39 Tahun',
    keterangan: '-',
    tingkatan: 4,
    tingkatLabel: 'Guru',
  },
  {
    id: 6,
    nama: 'Rina Wulandari, S.Pd.',
    nip: '199002152014022004',
    nuptk: '-',
    statusKepegawaian: 'PNS',
    pendidikan: 'S1 Pendidikan Bahasa Inggris',
    jabatan: 'Guru Bahasa Inggris',
    status: 'Guru',
    mataPelajaran: 'Bahasa Inggris',
    foto: 'images/GuruPegawai/guru-5.jpg',
    jenisKelamin: 'Perempuan',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 15 Februari 1990',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '36 Tahun',
    keterangan: '-',
    tingkatan: 4,
    tingkatLabel: 'Guru',
  },
  {
    id: 7,
    nama: 'Drs. Hadi Sucipto',
    nip: '196910101993031004',
    nuptk: '-',
    statusKepegawaian: 'PNS',
    pendidikan: 'S1 Pendidikan Sejarah',
    jabatan: 'Guru IPS',
    status: 'Guru',
    mataPelajaran: 'Ilmu Pengetahuan Sosial',
    foto: 'images/GuruPegawai/guru-6.jpg',
    jenisKelamin: 'Laki-laki',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 10 Oktober 1969',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '57 Tahun',
    keterangan: '-',
    tingkatan: 4,
    tingkatLabel: 'Guru',
  },
  {
    id: 8,
    nama: 'Nurul Hidayah, S.Pd.',
    nip: '199205202016022006',
    nuptk: '-',
    statusKepegawaian: 'PNS',
    pendidikan: 'S1 Seni Rupa',
    jabatan: 'Guru Seni Budaya',
    status: 'Guru',
    mataPelajaran: 'Seni Budaya',
    foto: 'images/GuruPegawai/guru-7.jpg',
    jenisKelamin: 'Perempuan',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 20 Mei 1992',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '34 Tahun',
    keterangan: '-',
    tingkatan: 4,
    tingkatLabel: 'Guru',
  },
  {
    id: 9,
    nama: 'Lestari Indah, S.Pd.',
    nip: '199108152015022010',
    nuptk: '-',
    statusKepegawaian: 'PNS',
    pendidikan: 'S1 Pendidikan Bahasa Indonesia',
    jabatan: 'Guru Bahasa Indonesia',
    status: 'Guru',
    mataPelajaran: 'Bahasa Indonesia',
    foto: 'images/GuruPegawai/guru-8.jpg',
    jenisKelamin: 'Perempuan',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 15 Agustus 1991',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '35 Tahun',
    keterangan: '-',
    tingkatan: 4,
    tingkatLabel: 'Guru',
  },
  {
    id: 10,
    nama: 'Walfa Hendri',
    nip: '-',
    nuptk: '-',
    statusKepegawaian: 'Honor Daerah TK.II Kab/Kota',
    pendidikan: 'SMA / sederajat',
    jabatan: 'Tenaga Administrasi Sekolah',
    status: 'Pegawai',
    jenisKelamin: 'Laki-laki',
    agama: 'Islam',
    tempatTanggalLahir: 'SIJUNJUNG, 10 March 1976',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '-',
    keterangan: '-',
    foto: 'images/GuruPegawai/pegawai-1.jpg',
    tingkatan: 5,
    tingkatLabel: 'Pegawai',
  },
  {
    id: 11,
    nama: 'Dewi Kusumawati',
    nip: '198003102005022008',
    nuptk: '-',
    statusKepegawaian: 'PNS',
    pendidikan: 'D3 Akuntansi',
    jabatan: 'Bendahara',
    status: 'Pegawai',
    foto: 'images/GuruPegawai/pegawai-2.jpg',
    jenisKelamin: 'Perempuan',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 10 Maret 1980',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '46 Tahun',
    keterangan: '-',
    tingkatan: 5,
    tingkatLabel: 'Pegawai',
  },
  {
    id: 12,
    nama: 'Eko Prasetyo',
    nip: '198810102010011009',
    nuptk: '-',
    statusKepegawaian: 'PNS',
    pendidikan: 'S1 Teknik Informatika',
    jabatan: 'Operator Sekolah',
    status: 'Pegawai',
    foto: 'images/GuruPegawai/pegawai-3.jpg',
    jenisKelamin: 'Laki-laki',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 10 Oktober 1988',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '38 Tahun',
    keterangan: '-',
    tingkatan: 5,
    tingkatLabel: 'Pegawai',
  },
  {
    id: 13,
    nama: 'Slamet Riyadi',
    nip: '197805152003011010',
    nuptk: '-',
    statusKepegawaian: 'Honor Sekolah',
    pendidikan: 'SMA / sederajat',
    jabatan: 'Satpam',
    status: 'Satpam',
    foto: 'images/GuruPegawai/satpam-1.jpg',
    jenisKelamin: 'Laki-laki',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 15 Mei 1978',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '48 Tahun',
    keterangan: '-',
    tingkatan: 6,
    tingkatLabel: 'Satpam',
  },
  {
    id: 14,
    nama: 'Wahyu Nugroho',
    nip: '198210202008011011',
    nuptk: '-',
    statusKepegawaian: 'Honor Sekolah',
    pendidikan: 'SMA / sederajat',
    jabatan: 'Satpam',
    status: 'Satpam',
    foto: 'images/GuruPegawai/satpam-2.jpg',
    jenisKelamin: 'Laki-laki',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 20 Oktober 1982',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '44 Tahun',
    keterangan: '-',
    tingkatan: 6,
    tingkatLabel: 'Satpam',
  },
  {
    id: 15,
    nama: 'Budi Santoso',
    nip: '198512122010011012',
    nuptk: '-',
    statusKepegawaian: 'Honor Sekolah',
    pendidikan: 'SMA / sederajat',
    jabatan: 'Satpam',
    status: 'Satpam',
    foto: 'images/GuruPegawai/satpam-3.jpg',
    jenisKelamin: 'Laki-laki',
    agama: 'Islam',
    tempatTanggalLahir: 'Sijunjung, 12 Desember 1985',
    alamat: '-',
    kodepos: '-',
    telepon: '-',
    instansi,
    umur: '41 Tahun',
    keterangan: '-',
    tingkatan: 6,
    tingkatLabel: 'Satpam',
  },
];
